import random
import string
import re
i = 0
while i == i:	
	print("What copypasta would you like to fuck up?")
	option = (input("Input 'tbf' for R&M copypasta, 'nm's fav' for NM's personal choice, 'fuck it' for a random copypasta, or 'me' to input your own meme\n> "))
	string = "empty!!!"
	if option == "tbf":
		string = "To be fair, you have to have a very high IQ to understand Rick and Morty. The humour is extremely subtle, and without a solid grasp of theoretical physics most of the jokes will go over a typical viewer's head. There's also Rick's nihilistic outlook, which is deftly woven into his characterisation- his personal philosophy draws heavily from Narodnaya Volya literature, for instance. The fans understand this stuff; they have the intellectual capacity to truly appreciate the depths of these jokes, to realise that they're not just funny- they say something deep about LIFE. As a consequence people who dislike Rick & Morty truly ARE idiots- of course they wouldn't appreciate, for instance, the humour in Rick's existential catchphrase 'Wubba Lubba Dub Dub,' which itself is a cryptic reference to Turgenev's Russian epic Fathers and Sons. I'm smirking right now just imagining one of those addlepated simpletons scratching their heads in confusion as Dan Harmon's genius wit unfolds itself on their television screens. What fools.. how I pity them. 😂 And yes, by the way, i DO have a Rick & Morty tattoo. And no, you cannot see it. It's for the ladies' eyes only- and even then they have to demonstrate that they're within 5 IQ points of my own (preferably lower) beforehand. Nothin personnel kid 😎"
		break
	elif option == "me":
		string = input("\nOkay, what would you like to fuck up?\n> ")
		break
	elif option == "nm's fav":
		string = "This is so sad Alexa play Despacito"
		break
	elif option == "fuck it":
		losslist = ["✋Excuse me sir ✋👏but 👏👉is that original post you made 👉right there 👉loss ❓☝Now hold on ☝😡it might sound ridiculous 😡😤but bare with me here. 😤👀You see 👀 there's 4️⃣ panels ☝let's count them ☝ 1️⃣ 2️⃣ 3️⃣ 4️⃣ panels ❗️❗️✋And you know what else has 4️⃣ panels ❓😤That's right 😤😡loss does ❗️😡 👇But i'm not done yet 👇 👀you see 👀👉in the first panel 👉☝there is ☝ 1️⃣ object 👈 positioned slightly to the left. 👈 😡Should I even continue ❓😡😤I guess I will 😤😒as you still don't understand. 😒 😲I should clarify this is a level 5 loss meme 😲🙄so I don't expect you to understand it. 🙄 💁‍ Anyways 💁‍ ✌️ in the second panel ✌️👀there are 2️⃣ objects 👀👉next to each other 👉 👇with one being slightly below the other. 👇☝ In the 3️⃣rd panel ☝ ✌️another 2️⃣ objects are present ✌️ 🙌right next to each other. 🙌 👆 Finally, 👆 there are, yet again, 2️⃣ objects 👆 🤙 which form an L shape. 🤙 👀Everything looks like it's adding up 👀😤therefore😤😡it HAS to be loss ❗️❗️😒You need to make it less obvious next time 😒🙄if you want it to be more funny. 🙄", 
		"The 💰 intent 💰 is 💰 to 💰 provide 💰 players 💰 with 💰 a 💰 sense 💰 of 💰 pride 💰 and 💰 accomplishment 💰 for 💰 unlocking 💰 different 💰 heroes. 💰 As 💰 for 💰 cost, 💰 we 💰 selected 💰 initial 💰 values 💰 based 💰 upon 💰 data 💰 from 💰 the 💰 Open 💰 Beta 💰 and 💰 other 💰 adjustments 💰 made 💰 to 💰 milestone 💰 rewards 💰 before 💰 launch. 💰 Among 💰 other 💰 things, 💰 we're 💰 looking 💰 at 💰 average 💰 per-player 💰 credit 💰 earn 💰 rates 💰 on 💰 a 💰 daily 💰 basis, 💰 and 💰 we'll 💰 be 💰 making 💰 constant 💰 adjustments 💰 to 💰 ensure 💰 that 💰 players 💰 have 💰 challenges 💰 that 💰 are 💰 compelling, 💰 rewarding, 💰 and 💰 of 💰 course 💰 attainable 💰 via 💰 gameplay. We 💰 appreciate 💰 the 💰 candid 💰 feedback, 💰 and 💰 the 💰 passion 💰 the 💰 community 💰 has 💰 put 💰 forth 💰 around 💰 the 💰 current 💰 topics 💰 here 💰 on 💰 Reddit, 💰 our 💰 forums 💰 and 💰 across 💰 numerous 💰 social 💰 media 💰 outlets. Our 💰 team 💰 will 💰 continue 💰 to 💰 make 💰 changes 💰 and 💰 monitor 💰 community 💰 feedback 💰 and 💰 update 💰 everyone 💰 as 💰 soon 💰 and 💰 as 💰 often 💰 as 💰 we 💰 can. 💰 💰", 
		"So today in Spanish class, my teacher told us that we would be listening to a song in Spanish. Already, I began to tremble. I had a bad feeling about this. “Which one?” I ask shakily, not wanting to hear the answer. “Despacito” She responds. I begin to hyperventilate. My worst fears have been realized. I fade in and out of conciseness. I clamp my palms over my ears, but I know it’s futile. The song plays. I’m crying now, praying. God, Allah, Buddha please help me. I curl up on the floor. There’s nothing I can do now. And then it happens. The chorus plays. The girls in my class open their mouths. The screams of the damned, the shrieks of the tortured fill my ears and bounce around my skull. My eardrums rupture, blood leaking out. I try to scream, but no sound comes out. I can only sit there, violently shaking as it happens to me. After what seems like hours, it’s finally over. I try to move, but I cannot make myself. My brain shuts down as my vision fades to black. I muster the last of my energy, uttering the accursed word. 'Despacito'", 
		"How exactly does one get pussy while living at the white house as a teenage boy? The secret service always cock blocking you. when you're trying to run game on some foreign prime ministers daughter the news media catches you smiling at her and immediately blows shit out if proportion speculating that you are somehow breaking international law with your awkward teenage flirting, so you have to testify before congress that you didn't give away any top secret documents to her and are made to admit live on C-SPAN that you've never even kissed a girl . Then you get blue balls from some hot conservative girl winking at you and flashing her panties under her skirt and making sexy faces and blow job motions to you while you were going through some airport or public event, and when you passed by and shook her hand she leans in whispering she is going to diddle her clit thinking about you tonight and how much she wants to suck your dick off, just to fuck with you. Then you try to look up some porn when you get home just to relieve the tension but you just know the CIA is monitoring and 3 other govornment agencies are watching you beat off. Then you finally break down and Jack off in the shower which sets off some fucking biohazard drain alarm and the entire place is on lock down until they can find the source of the specimen and you end up getting debriefed by the joint chiefs of staff about your masturbatory habits and how you almost created a national security issue with your dick. Then wikileaks leaks your search history showing you looked up penis enlargement techniques when it was actually just some click bait you'd accidentally clicked and TYT spends all next week talking about your supposed micro penis. So you end up squirming a little since you are so wound up and being judged constantly and now people are saying you look like a fucking mental patient and you start to think you'll never get any pussy.", 
		"OMG 😱😱😱 BRO👬 CALM 😴😴 DOWN BRO ⬇️⬇️ SIMMER ☕️☕️ DOWN⬇️⬇️ U WANNA KNOW Y⁉️ BC 💁💁 IT WAS JUST A PRANK 😂😂😂 😛😜 HAHAHA GOT U 👌👌 U FUKIN RETARD 😂😁😁THERE'S A CAMERA 📹📷 RIGHT OVER 👈👇👆☝️ THERE"]
		leng = len(losslist)-1
		string = losslist[random.randint(0, leng)]
		break	
	else:
		print("That's not an option my dude...\n")
		i += 1
randcase = []
wordbreak = list(re.sub(r"[^\w\s]", "", string, re.UNICODE))
for letter in wordbreak:
	if random.randint(1,2) == 1:
		randcase.append(str.upper(letter))
	else:
		randcase.append(str.lower(letter))
randcasestr = "".join(randcase)
memelist = randcasestr.split()
print("\nOkay, here you go:")
print(" ".join(random.sample(memelist, len(memelist))))